/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Prediction = IDL.Record({
  'predictedNumber' : IDL.Nat,
  'timestamp' : Time,
  'confidence' : IDL.Nat,
  'outcome' : IDL.Text,
});

export const idlService = IDL.Service({
  'generatePrediction' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [Prediction],
      [],
    ),
  'getPredictionHistory' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Prediction = IDL.Record({
    'predictedNumber' : IDL.Nat,
    'timestamp' : Time,
    'confidence' : IDL.Nat,
    'outcome' : IDL.Text,
  });
  
  return IDL.Service({
    'generatePrediction' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [Prediction],
        [],
      ),
    'getPredictionHistory' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };